#!/usr/bin/env ruby

map = {
  "office-ui-fabric-react/lib/components/ActivityItem/ActivityItem.doc"                                =>"office-ui-fabric-react/lib/packages/react-cards/components/ActivityItem/ActivityItem.doc",
  "office-ui-fabric-react/lib/components/Announced/Announced.doc"                                      =>"office-ui-fabric-react/lib/packages/react-primitives/components/Announced/Announced.doc",
  "office-ui-fabric-react/lib/components/Breadcrumb/Breadcrumb.doc"                                    =>"office-ui-fabric-react/lib/packages/react-commanding/components/Breadcrumb/Breadcrumb.doc",
  "office-ui-fabric-react/lib/components/Button/Button.doc"                                            =>"office-ui-fabric-react/lib/packages/react-inputs/components/Button/Button.doc",
  "office-ui-fabric-react/lib/components/Calendar/Calendar.doc"                                        =>"office-ui-fabric-react/lib/packages/react-date-time/components/Calendar/Calendar.doc",
  "office-ui-fabric-react/lib/components/Callout/Callout.doc"                                          =>"office-ui-fabric-react/lib/packages/react-surfaces/components/Callout/Callout.doc",
  "office-ui-fabric-react/lib/components/Checkbox/Checkbox.doc"                                        =>"office-ui-fabric-react/lib/packages/react-inputs/components/Checkbox/Checkbox.doc",
  "office-ui-fabric-react/lib/components/ChoiceGroup/ChoiceGroup.doc"                                  =>"office-ui-fabric-react/lib/packages/react-inputs/components/ChoiceGroup/ChoiceGroup.doc",
  "office-ui-fabric-react/lib/components/Coachmark/Coachmark.doc"                                      =>"office-ui-fabric-react/lib/packages/react-notifications/components/Coachmark/Coachmark.doc",
  "office-ui-fabric-react/lib/components/Coachmark/PositioningContainer/PositioningContainer.doc"      =>"office-ui-fabric-react/lib/packages/react-notifications/components/Coachmark/PositioningContainer/PositioningContainer.doc",
  "office-ui-fabric-react/lib/components/ColorPicker/ColorPicker.doc"                                  =>"office-ui-fabric-react/lib/packages/react-pickers/components/ColorPicker/ColorPicker.doc",
  "office-ui-fabric-react/lib/components/ComboBox/ComboBox.doc"                                        =>"office-ui-fabric-react/lib/packages/react-inputs/components/ComboBox/ComboBox.doc",
  "office-ui-fabric-react/lib/components/CommandBar/CommandBar.doc"                                    =>"office-ui-fabric-react/lib/packages/react-commanding/components/CommandBar/CommandBar.doc",
  "office-ui-fabric-react/lib/components/ContextualMenu/ContextualMenu.doc"                            =>"office-ui-fabric-react/lib/packages/react-contextual-menu/components/ContextualMenu/ContextualMenu.doc",
  "office-ui-fabric-react/lib/components/DatePicker/DatePicker.doc"                                    =>"office-ui-fabric-react/lib/packages/react-date-time/components/DatePicker/DatePicker.doc",
  "office-ui-fabric-react/lib/components/DetailsList/DetailsList.doc"                                  =>"office-ui-fabric-react/lib/packages/react-data-views/components/DetailsList/DetailsList.doc",
  "office-ui-fabric-react/lib/components/DetailsList/examples/DetailsList.Basic.Example"               =>"office-ui-fabric-react/lib/packages/react-data-views/components/DetailsList/examples/DetailsList.Basic.Example",
  "office-ui-fabric-react/lib/components/Dialog/Dialog.doc"                                            =>"office-ui-fabric-react/lib/packages/react-surfaces/components/Dialog/Dialog.doc",
  "office-ui-fabric-react/lib/components/Divider/Divider.doc"                                          =>"office-ui-fabric-react/lib/packages/react-primitives/components/Divider/Divider.doc",
  "office-ui-fabric-react/lib/components/DocumentCard/DocumentCard.doc"                                =>"office-ui-fabric-react/lib/packages/react-cards/components/DocumentCard/DocumentCard.doc",
  "office-ui-fabric-react/lib/components/Dropdown/Dropdown.doc"                                        =>"office-ui-fabric-react/lib/packages/react-inputs/components/Dropdown/Dropdown.doc",
  "office-ui-fabric-react/lib/components/ExtendedPicker/PeoplePicker/ExtendedPeoplePicker.doc"         =>"office-ui-fabric-react/lib/packages/react-pickers/components/ExtendedPicker/PeoplePicker/ExtendedPeoplePicker.doc",
  "office-ui-fabric-react/lib/components/Facepile/Facepile.doc"                                        =>"office-ui-fabric-react/lib/packages/react-people/components/Facepile/Facepile.doc",
  "office-ui-fabric-react/lib/components/FloatingPicker/PeoplePicker/FloatingPeoplePicker.doc"         =>"office-ui-fabric-react/lib/packages/react-pickers/components/FloatingPicker/PeoplePicker/FloatingPeoplePicker.doc",
  "office-ui-fabric-react/lib/components/FocusTrapZone/FocusTrapZone.doc"                              =>"office-ui-fabric-react/lib/packages/react-focus/components/FocusTrapZone/FocusTrapZone.doc",
  "office-ui-fabric-react/lib/components/FocusZone/FocusZone.doc"                                      =>"office-ui-fabric-react/lib/packages/react-focus/components/FocusZone/FocusZone.doc",
  "office-ui-fabric-react/lib/components/GroupedList/GroupedList.doc"                                  =>"office-ui-fabric-react/lib/packages/react-data-views/components/GroupedList/GroupedList.doc",
  "office-ui-fabric-react/lib/components/HoverCard/HoverCard.doc"                                      =>"office-ui-fabric-react/lib/packages/react-cards/components/HoverCard/HoverCard.doc",
  "office-ui-fabric-react/lib/components/Icon/Icon.doc"                                                =>"office-ui-fabric-react/lib/packages/react-primitives/components/Icon/Icon.doc",
  "office-ui-fabric-react/lib/components/Image/Image.doc"                                              =>"office-ui-fabric-react/lib/packages/react-primitives/components/Image/Image.doc",
  "office-ui-fabric-react/lib/components/Keytip/Keytips.doc"                                           =>"office-ui-fabric-react/lib/packages/react-primitives/components/Keytip/Keytips.doc",
  "office-ui-fabric-react/lib/components/Label/Label.doc"                                              =>"office-ui-fabric-react/lib/packages/react-inputs/components/Label/Label.doc",
  "office-ui-fabric-react/lib/components/Layer/Layer.doc"                                              =>"office-ui-fabric-react/lib/packages/react-surfaces/components/Layer/Layer.doc",
  "office-ui-fabric-react/lib/components/Link/Link.doc"                                                =>"office-ui-fabric-react/lib/packages/react-primitives/components/Link/Link.doc",
  "office-ui-fabric-react/lib/components/List/List.doc"                                                =>"office-ui-fabric-react/lib/packages/react-data-views/components/List/List.doc",
  "office-ui-fabric-react/lib/components/MarqueeSelection/MarqueeSelection.doc"                        =>"office-ui-fabric-react/lib/packages/react-data-views/components/MarqueeSelection/MarqueeSelection.doc",
  "office-ui-fabric-react/lib/components/MessageBar/MessageBar.doc"                                    =>"office-ui-fabric-react/lib/packages/react-notifications/components/MessageBar/MessageBar.doc",
  "office-ui-fabric-react/lib/components/Modal/Modal.doc"                                              =>"office-ui-fabric-react/lib/packages/react-surfaces/components/Modal/Modal.doc",
  "office-ui-fabric-react/lib/components/Nav/Nav.doc"                                                  =>"office-ui-fabric-react/lib/packages/react-commanding/components/Nav/Nav.doc",
  "office-ui-fabric-react/lib/components/OverflowSet/OverflowSet.doc"                                  =>"office-ui-fabric-react/lib/packages/react-commanding/components/OverflowSet/OverflowSet.doc",
  "office-ui-fabric-react/lib/components/Overlay/Overlay.doc"                                          =>"office-ui-fabric-react/lib/packages/react-surfaces/components/Overlay/Overlay.doc",
  "office-ui-fabric-react/lib/components/Panel/Panel.doc"                                              =>"office-ui-fabric-react/lib/packages/react-surfaces/components/Panel/Panel.doc",
  "office-ui-fabric-react/lib/components/Persona/Persona.doc"                                          =>"office-ui-fabric-react/lib/packages/react-people/components/Persona/Persona.doc",
  "office-ui-fabric-react/lib/components/Pivot/Pivot.doc"                                              =>"office-ui-fabric-react/lib/packages/react-commanding/components/Pivot/Pivot.doc",
  "office-ui-fabric-react/lib/components/ProgressIndicator/ProgressIndicator.doc"                      =>"office-ui-fabric-react/lib/packages/react-notifications/components/ProgressIndicator/ProgressIndicator.doc",
  "office-ui-fabric-react/lib/components/ProgressIndicator/examples/ProgressIndicator.Basic.Example"   =>"office-ui-fabric-react/lib/packages/react-notifications/components/ProgressIndicator/examples/ProgressIndicator.Basic.Example",
  "office-ui-fabric-react/lib/components/Rating/Rating.doc"                                            =>"office-ui-fabric-react/lib/packages/react-inputs/components/Rating/Rating.doc",
  "office-ui-fabric-react/lib/components/ResizeGroup/ResizeGroup.doc"                                  =>"office-ui-fabric-react/lib/packages/react-commanding/components/ResizeGroup/ResizeGroup.doc",
  "office-ui-fabric-react/lib/components/ScrollablePane/ScrollablePane.doc"                            =>"office-ui-fabric-react/lib/packages/react-surfaces/components/ScrollablePane/ScrollablePane.doc",
  "office-ui-fabric-react/lib/components/SearchBox/SearchBox.doc"                                      =>"office-ui-fabric-react/lib/packages/react-inputs/components/SearchBox/SearchBox.doc",
  "office-ui-fabric-react/lib/components/SelectedItemsList/SelectedPeopleList/SelectedPeopleList.doc"  =>"office-ui-fabric-react/lib/packages/react-data-views/components/SelectedItemsList/SelectedPeopleList/SelectedPeopleList.doc",
  "office-ui-fabric-react/lib/components/Separator/Separator.doc"                                      =>"office-ui-fabric-react/lib/packages/react-primitives/components/Separator/Separator.doc",
  "office-ui-fabric-react/lib/components/Shimmer/Shimmer.doc"                                          =>"office-ui-fabric-react/lib/packages/react-notifications/components/Shimmer/Shimmer.doc",
  "office-ui-fabric-react/lib/components/Slider/Slider.doc"                                            =>"office-ui-fabric-react/lib/packages/react-inputs/components/Slider/Slider.doc",
  "office-ui-fabric-react/lib/components/SpinButton/SpinButton.doc"                                    =>"office-ui-fabric-react/lib/packages/react-inputs/components/SpinButton/SpinButton.doc",
  "office-ui-fabric-react/lib/components/Spinner/Spinner.doc"                                          =>"office-ui-fabric-react/lib/packages/react-notifications/components/Spinner/Spinner.doc",
  "office-ui-fabric-react/lib/components/Stack/Stack.doc"                                              =>"office-ui-fabric-react/lib/packages/react-primitives/components/Stack/Stack.doc",
  "office-ui-fabric-react/lib/components/SwatchColorPicker/SwatchColorPicker.doc"                      =>"office-ui-fabric-react/lib/packages/react-pickers/components/SwatchColorPicker/SwatchColorPicker.doc",
  "office-ui-fabric-react/lib/components/TeachingBubble/TeachingBubble.doc"                            =>"office-ui-fabric-react/lib/packages/react-notifications/components/TeachingBubble/TeachingBubble.doc",
  "office-ui-fabric-react/lib/components/TeachingBubble/examples/TeachingBubble.Basic.Example"         =>"office-ui-fabric-react/lib/packages/react-notifications/components/TeachingBubble/examples/TeachingBubble.Basic.Example",
  "office-ui-fabric-react/lib/components/Text/Text.doc"                                                =>"office-ui-fabric-react/lib/packages/react-primitives/components/Text/Text.doc",
  "office-ui-fabric-react/lib/components/TextField/TextField.doc"                                      =>"office-ui-fabric-react/lib/packages/react-inputs/components/TextField/TextField.doc",
  "office-ui-fabric-react/lib/components/TextField/examples/TextField.Basic.Example"                   =>"office-ui-fabric-react/lib/packages/react-inputs/components/TextField/examples/TextField.Basic.Example",
  "office-ui-fabric-react/lib/components/Theme/Theme.doc"                                              =>"office-ui-fabric-react/lib/components/Theme/Theme.doc",
  "office-ui-fabric-react/lib/components/Theme/ThemePage.styles"                                       =>"office-ui-fabric-react/lib/components/Theme/ThemePage.styles",
  "office-ui-fabric-react/lib/components/Theme/ThemePage.types"                                        =>"office-ui-fabric-react/lib/components/Theme/ThemePage.types",
  "office-ui-fabric-react/lib/components/Theme/defaultTheme"                                           =>"office-ui-fabric-react/lib/components/Theme/defaultTheme",
  "office-ui-fabric-react/lib/components/Toggle/Toggle.doc"                                            =>"office-ui-fabric-react/lib/packages/react-inputs/components/Toggle/Toggle.doc",
  "office-ui-fabric-react/lib/components/Toggle/examples/Toggle.Basic.Example"                         =>"office-ui-fabric-react/lib/packages/react-inputs/components/Toggle/examples/Toggle.Basic.Example",
  "office-ui-fabric-react/lib/components/Tooltip/Tooltip.doc"                                          =>"office-ui-fabric-react/lib/packages/react-surfaces/components/Tooltip/Tooltip.doc",
  "office-ui-fabric-react/lib/components/pickers/Pickers.doc"                                          =>"office-ui-fabric-react/lib/packages/react-pickers/components/pickers/Pickers.doc",
  "office-ui-fabric-react/lib/packages/react-pickers/components/pickers/PeoplePicker/PeoplePicker.doc" =>"office-ui-fabric-react/lib/packages/react-pickers/components/pickers/PeoplePicker/PeoplePicker.doc"
}

Dir['./**/*.ts*'].each do |file|
  contents = File.read(file)
  map.each do |needle, new_needle|
    contents.gsub!(needle, new_needle)
  end
  File.open(file, 'w') { |f| f.print contents }
  STDERR.puts file
end
